config/routes.rb
Todolist::Application.routes.draw do

  devise_for :users
  
  resources :users, only: [:index, :splash]

  scope '(:locale)' do
    resources :tags
    
    resources :todos do
      member do
        post :finished
        delete :remove_tag, to: 'todos#remove_tag'
        post :add_tag, to: 'todos#add_tag'
      end
      
      collection do
      end
      
    end
    
    resources :users do
      member do
        get :clear_search, to: 'users#clear_search'
        delete :remove_all_complete, to: 'users#remove_all_complete'
      end
    end
    
    authenticated :user do
      root :to => "users#index"
    end
    
    root :to => 'users#splash'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # User has many todos
  has_many :todos
  has_many :tags
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  # For searching
  def search(phrase)
    if phrase
      self.todos.find(:all, conditions: ['todo LIKE ?', "%#{phrase}%"])
    else
      self.todos.find(:all)
    end
  end
  
  def search_count(phrase)
    self.search(phrase).size
  end
  
  # Statistics
  def count
    self.todos.size
  end
  
  def incomplete_count
    sum = 0
    
    self.todos.each do |todo|
      if todo.done == false
        sum += 1
      end
    end
    
    sum
  end
  
  def remove_all_complete
    self.todos.each do |todo|
      if todo.done == true
        todo.destroy
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    
    # Restrict to only todos owned by the user
    @todos = Todo.where(user_id: @user.id)
    if params[:filter_tag_id].present?
      @tag = Tag.find_by_id(params[:filter_tag_id])
      if @tag
        @todos = @tag.todos
      end
    end
    
    # Reference for pagination help:
    # http://fourthslap.blogspot.jp/2011/04/kaminari-beautiful-pagination-gem-for.html
    if params[:search].present?
      array = @user.search(params[:search])
      @todos_paged = Kaminari::PaginatableArray.new( array ).page(params[:page])
      @total_todos = array.size
    else
      @todos_paged = @todos.page(params[:page])
      @total_todos = @todos.size
    end
  end
  
  def splash
  end

  def remove_all_complete
    @user = current_user
    @user.remove_all_complete

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
  
  def clear_search
    params[:search] = nil
    render index
  end
  
end

app/views/users/_listing.html.erb
<table>
<% @todos_paged.each do |todo| %>
  <tr>
    <td>
      <% if todo.done %>
        <font color="gray"><strike><%= todo.todo %></strike></font>
      <% else %>
        <%= todo.todo %>
      <% end %>
    </td>
    <td><%= button_to t('.edit'), edit_todo_path(todo), method: :get, class: 'btn btn-default' %></td>
    <td>
      <%= button_to t('.finished'), finished_todo_path(todo), class: 'btn btn-default' unless todo.done %>
    </td>
    <td><%= button_to t('.delete'), todo, method: :delete, data: { confirm: t('are_you_sure?') }, class: 'btn btn-danger' %></td>
    <td><% if todo.tags.size > 0 %><%= t('.tags') %>: <font color="gray"><%= todo.tags_comma_list %></font><% end %></td>
  </tr>
<% end %>
</table>

<% if (@user.count - @user.incomplete_count) > 0 %>
  <%= button_to t('.remove_all_complete'), remove_all_complete_user_path(@user), method: :delete,
    data: { confirm: t('are_you_sure?') }, class: 'btn btn-danger' %>
<% end %>

<%= button_to t('.new_todo'), new_todo_path, method: :get, class: 'btn btn-primary' %>
  
<%= button_to t('.tags_all'), tags_path, method: :get, class: 'btn btn-primary' %>

<hr>
  
<%= paginate @todos_paged %>

<br />

<p><%= t('.remaining_tasks') %>: <%= @user.incomplete_count %> <%= t('.out_of') %> <%= @user.count %></p>

app/views/users/_search.html.erb
<p>
  <table>
    <tr>
      <td>
        <%= form_tag root_path, method: 'get' do %>
          <%= submit_tag t('.search'), todo: nil, class: 'btn btn-default' %>
          <%= text_field_tag :search, params[:search] %>
        <% end %>
      </td>
      <td></td>
      <td>
      
        <%= form_tag root_path, method: 'get' do %>
          <%= submit_tag t('.tag_filter'), todo: nil, class: 'btn btn-default' %>
          <%= select_tag("filter_tag_id", options_from_collection_for_select(current_user.tags, :id, :title), include_blank: true) %>
        <% end %>
        
      </td>
    </tr>
    
    <% if params[:search].present? || params[:filter_tag_id].present? %>
      <tr>
        <td>
          <%= button_to t('.clear_filters'), root_path, method: :get, class: 'btn btn-default' %>
          <p><%= t('.found_front') %><%= @total_todos %><%= t('.found_back') %></p>
          <hr>
        </td>
      </tr>
    <% end %>
  </table>
</p>

app/views/users/index.html.erb
<%= render "search" %>

<%= render "listing" %>

app/views/users/splash.html.erb
<p><%= t('.message') %></p>
<%= link_to t('devise.sign_in'), new_user_session_path, method: :get %>
<%= link_to t('devise.sign_up'), new_user_registration_path, method: :get %>