config/routes.rb
Todolist::Application.routes.draw do

  devise_for :users
  
  resources :users, only: [:index, :splash]

  scope '(:locale)' do
    resources :tags
    
    resources :todos do
      member do
        post :finished
        delete :remove_tag, to: 'todos#remove_tag'
        post :add_tag, to: 'todos#add_tag'
      end
      
      collection do
      end
      
    end
    
    resources :users do
      member do
        get :clear_search, to: 'users#clear_search'
        delete :remove_all_complete, to: 'users#remove_all_complete'
      end
    end
    
    authenticated :user do
      root :to => "users#index"
    end
    
    root :to => 'users#splash'
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # All tags associated with a single user must be unique
  validates_uniqueness_of :title, scope: :user_id

  attr_accessible :title
  
  belongs_to :user
  has_and_belongs_to_many :todos
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = current_user.tags

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = current_user.tags.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])
    @tag.user = current_user

    respond_to do |format|
      if @tag.save
        # If we came from editing a Todo, go back there
        if params[:return_todo_id].present?
          format.html { redirect_to edit_todo_path(id: params[:return_todo_id]), notice: t('tags.success_create') }
        else
          format.html { redirect_to @tag, notice: t('tags.success_create') }
        end
        format.html { redirect_to @tag, notice: t('tags.success_create') }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: t('tags.success_update') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag, url: tags_path(return_todo_id: params[:return_todo_id])) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> <%= t('error_msg') %>:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <% if params[:return_todo_id].present? %><%#= params[:return_todo_id] %><% end %>
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.title %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @tag.title %>
</p>
<p>
  <b>User:</b>
  <% if @tag.user %>
    <%= @tag.user.email %>
  <% end %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>