config/routes.rb
Todolist::Application.routes.draw do

  devise_for :users
  
  resources :users, only: [:index, :splash]

  scope '(:locale)' do
    resources :tags
    
    resources :todos do
      member do
        post :finished
        delete :remove_tag, to: 'todos#remove_tag'
        post :add_tag, to: 'todos#add_tag'
      end
      
      collection do
      end
      
    end
    
    resources :users do
      member do
        get :clear_search, to: 'users#clear_search'
        delete :remove_all_complete, to: 'users#remove_all_complete'
      end
    end
    
    authenticated :user do
      root :to => "users#index"
    end
    
    root :to => 'users#splash'
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :done, :todo, :user_id
  
  belongs_to :user
  
  has_and_belongs_to_many :tags
  
  paginates_per 5
  
  validates :todo, presence: true
  
  # Want to initialize done to false (i.e. incomplete task)
  after_initialize :default_values
  def default_values
    # Set if not nil
    self.done ||= false
  end
  
  def add_tag_with_id(new_tag_id)
    # The 'new_tag_id' is 0 if no new tag to add, and the tag_id of a new tag otherwise
    new_tag = Tag.find_by_id(new_tag_id)
    
    # If the tag exists and is not already present
    if (new_tag) && (self.tags.where(id: new_tag_id).present? == false)
      self.tags << new_tag
    end
  end
  
  def remaining_tags
    # Get all tags owned by this user, not including tags currently used by this Todo
    self.user.tags - self.tags
  end

  def tags_comma_list
    string = ''
    self.tags.each_with_index do |tag, index|
      if index > 0
        string += ', '
      end
      string += tag.title
    end
    string
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    @user = current_user
    @tags = @user.tags

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])
    #@todos = Todo.where(:id>=0).order("id asc").page(params[:page]).per(3)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(params[:todo])
    # Set the user who owns this
    @todo.user = current_user

    respond_to do |format|
      if @todo.save
        format.html { redirect_to root_path, notice: t('todos.success_create') }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])
    
    # If the button was ther "Add tag" button, only need to process the new tag
    if params[:add_tag].present?

      # Only call if the given tag exists for the current user
      if current_user.tags.find_by_id(params[:new_tag_id])
        @todo.add_tag_with_id(params[:new_tag_id])
      end
      
      respond_to do |format|
        format.html { redirect_to edit_todo_path, notice: t('todos.success_add') }
        format.json { head :no_content }
      end
      
    # Here, we are doing a regular update of :todo and :done
    else
    
      respond_to do |format|
      # new_tag_id is not an actual attribute of Todo, so it must be removed from
      # the params[:todo] hash before calling update_attributes below
      if @todo.update_attributes(params[:todo])
          format.html { redirect_to root_path, notice: t('todos.success_update') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @todo.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: t('todos.success_destroy') }
      format.json { head :no_content }
    end
  end
  
  def finished
    @todo = Todo.find(params[:id])
    @todo.done = true
    @todo.save
    
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
  
  def remove_tag
    @todo = Todo.find(params[:todo_id])
    @todo.tags.delete(Tag.find_by_id(params[:tag_id]))

    respond_to do |format|
      format.html { redirect_to edit_todo_path, notice: t('todos.tag_removed') }
      format.json { head :no_content }
    end
  end
  
  def add_tag
    Rails.logger.debug("DEBUG add_tag: #{params[:tag_id]}")
    @todo = Todo.find(params[:id])
    @todo.add_tag_with_id(params[:tag_id])

    respond_to do |format|
      format.html { redirect_to edit_todo_path, notice: t('todos.tag_added') }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/todos_helper.rb
module TodosHelper

end

app/views/todos/_form.html.erb
<%= simple_form_for @todo, :html => { class: 'form-horizontal' } do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> <%= t('error_msg') %>:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :todo, input_html: { class: "span6" } %>
  <% if f.object.new_record? == false %>
    <%= f.input :done, label: t('.done'), as: :boolean %>

    <h4><%= t('.tags') %></h4>
    <table class="table">
    <% @todo.tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= link_to t('.remove_tag'), remove_tag_todo_path(todo_id: @todo, tag_id: tag), controller: :todo, method: :delete %></td>
      </tr>
    <% end %>
    
    <% if @todo.remaining_tags.size > 0 %>
      <tr>
        <td>
          <select name="new_tag_id">
            <option value="0"></option>
            <% @todo.remaining_tags.each do |tag| %>
                <option value="<%= tag.id %>"><%= tag.title %></option>
            <% end %>
          </select>
        </td>
        <td>
          <%= f.submit t('.add_tag'), method: :post, class: 'btn btn-default', name: :add_tag %>
        </td>
      </tr>
    <% end %>
    </table>
    <%= link_to t('.create_new_tag'), new_tag_path(return_todo_id: @todo.id) %>
  <% end %>
  
  <div class="form-actions">
    
    <% if f.object.new_record? %>
      <%= f.button :submit, :class => 'btn-primary' %>
    <% else %>
      <%= button_to t('.update'), f.object, method: :post, class: 'btn btn-primary' %>
      <%= button_to t('.delete'), f.object, method: :delete, data: { confirm: t('are_you_sure?') }, class: 'btn btn-danger' %>  
    <% end %>
    
  </div>
<% end %>

app/views/todos/edit.html.erb
<h3><%= t('.edit') %></h3>
<hr>

<%= render 'form' %>

<%= link_to t('.back'), root_path %>

app/views/todos/new.html.erb
<h3><%= t('.new') %></h3>
<hr>

<%= render 'form' %>

<%= link_to t('.back'), root_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Todo:</b>
  <%= @todo.todo %>
</p>

<p>
  <b>Done:</b>
  <%= @todo.done %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>